portfolio_controllers:
    resource: ../../src/Portfolios/Infrastructure/Portfolio/Web/Controller
    type: annotation
    prefix: api

order_controllers:
    resource: ../../src/Portfolios/Infrastructure/Order/Web/Controller
    type: annotation
    prefix: api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
