services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Portfolios\Domain\Portfolio\PortfolioRepository:
    class: App\Portfolios\Infrastructure\Portfolio\Persistence\DoctrinePortfolioRepository
    public: true

  App\Portfolios\Domain\Order\OrderRepository:
    class: App\Portfolios\Infrastructure\Order\Persistence\DoctrineOrderRepository
    public: true

  App\Portfolios\Domain\Allocation\AllocationRepository:
    class: App\Portfolios\Infrastructure\Allocation\Persistence\DoctrineAllocationRepository
    public: true

  App\Tests\Portfolios\Behat\:
    resource: '../tests/Portfolios/Behat/*'
