services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Portfolio\PortfolioRepository:
    class: App\Infrastructure\Portfolio\Persistence\DoctrinePortfolioRepository
    public: true

  App\Domain\Order\OrderRepository:
    class: App\Infrastructure\Order\Persistence\DoctrineOrderRepository
    public: true

  App\Domain\Allocation\AllocationRepository:
    class: App\Infrastructure\Allocation\Persistence\DoctrineAllocationRepository
    public: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'
